import { spawn } from "node:child_process";
import { stat } from "node:fs/promises";

const baseUrl = process.env.SMOKE_BASE_URL || "http://localhost:3000";
let serverProcess = null;

try {
  await ensureServer();
  await runSmoke();
  console.log("Phase 2 smoke test passed.");
} finally {
  if (serverProcess) serverProcess.kill();
}

async function runSmoke() {
  const templates = await get("/api/templates");
  assert(Array.isArray(templates.templates) && templates.templates.length > 0, "Template list returns data");

  const projectResponse = await post("/api/projects", {
    name: `Smoke Factory ${Date.now()}`,
    industry: "Professional services",
    goal: "Generate qualified leads through a professional service website.",
    audience: "Business owners",
    palette: "forest",
    templateId: templates.templates[0].id,
    pages: ["Home", "Services", "FAQ", "Contact"]
  });
  const projectId = projectResponse.project.id;
  assert(projectId, "Project creation works");

  const detail = await get(`/api/projects/${projectId}`);
  assert(detail.project.id === projectId, "Project detail fetch works");

  const patched = await patch(`/api/projects/${projectId}/config`, {
    business: {
      name: "Smoke Factory Updated",
      tagline: "A practical website factory smoke test.",
      industry: "Professional services",
      location: "Local",
      email: "hello@example.com",
      phone: "+1 555 0100"
    },
    branding: {
      primaryColor: "#176b5b",
      accentColor: "#d88c4a",
      darkMode: true
    },
    template: {
      selected: templates.templates[0].id
    },
    seo: {
      title: "Smoke Factory Updated",
      description: "A test website generated by the Website Factory Phase 2 smoke test."
    }
  });
  assert(patched.project.config.business.name === "Smoke Factory Updated", "Config patch works");

  const backup = await post(`/api/projects/${projectId}/backups`, { reason: "smoke-manual" });
  assert(backup.backup.backupId, "Backup creation works");

  const backups = await get(`/api/projects/${projectId}/backups`);
  assert(backups.backups.length >= 1, "Backup list works");

  const recon = await post(`/api/projects/${projectId}/agents/recon`);
  assert(recon.agent.lastRun, "Recon agent endpoint works");

  const security = await post(`/api/projects/${projectId}/agents/security`);
  assert(security.agent.lastRun, "Security agent endpoint works");

  const verifyBeforeBuild = await post(`/api/projects/${projectId}/agents/verify`);
  assert(verifyBeforeBuild.agent.lastRun, "Verify agent endpoint works");

  const backupAgent = await post(`/api/projects/${projectId}/agents/backup`);
  assert(backupAgent.agent.lastRun, "Backup agent endpoint works");

  const build = await post(`/api/projects/${projectId}/build`);
  assert(build.build.status === "success", "Build endpoint works");
  assert(build.build.previewPath && build.build.previewPath.includes(projectId), "Build creates preview metadata/path");
  await stat(`.${build.build.previewPath.replace("/previews", "/data/previews")}`);

  const builds = await get(`/api/projects/${projectId}/builds`);
  assert(builds.builds.some((item) => item.buildId === build.build.buildId), "Build list returns created build");

  const rollback = await post(`/api/projects/${projectId}/rollback/${backup.backup.backupId}`);
  assert(rollback.status === "rolled-back", "Rollback works");

  await import("./validate-data.js");
}

async function ensureServer() {
  try {
    await get("/api/templates");
  } catch {
    serverProcess = spawn("node", ["src/server/index.js"], { stdio: "ignore" });
    await waitForServer();
  }
}

async function waitForServer() {
  const started = Date.now();
  while (Date.now() - started < 10000) {
    try {
      await get("/api/templates");
      return;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
  }
  throw new Error("Server did not start within 10 seconds.");
}

async function get(path) {
  return request(path);
}

async function post(path, body = {}) {
  return request(path, { method: "POST", body });
}

async function patch(path, body) {
  return request(path, { method: "PATCH", body });
}

async function request(path, options = {}) {
  const response = await fetch(`${baseUrl}${path}`, {
    method: options.method || "GET",
    headers: options.body ? { "content-type": "application/json" } : undefined,
    body: options.body ? JSON.stringify(options.body) : undefined
  });
  const payload = await response.json();
  if (!response.ok) throw new Error(`${options.method || "GET"} ${path} failed: ${JSON.stringify(payload)}`);
  return payload;
}

function assert(condition, message) {
  if (!condition) throw new Error(`Smoke assertion failed: ${message}`);
}
